development:
  cloud_name: <%= Rails.application.credentials.cloudinary[:CLOUD_NAME] %>
  api_key: <%= Rails.application.credentials.cloudinary[:CLOUDINARY_API_KEY] %>
  api_secret: <%= Rails.application.credentials.cloudinary[:CLOUDINARY_API_SECRET] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= Rails.application.credentials.cloudinary[:CLOUD_NAME] %>
  api_key: <%= Rails.application.credentials.cloudinary[:CLOUDINARY_API_KEY] %>
  api_secret: <%= Rails.application.credentials.cloudinary[:CLOUDINARY_API_SECRET] %>
  enhance_image_tag: true
  static_file_support: false
test:
  cloud_name: <%= Rails.application.credentials.cloudinary[:CLOUD_NAME] %>
  api_key: <%= Rails.application.credentials.cloudinary[:CLOUDINARY_API_KEY] %>
  api_secret: <%= Rails.application.credentials.cloudinary[:CLOUDINARY_API_SECRET] %>
  enhance_image_tag: true
  static_file_support: false
