:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 10
:queues:
  - default
:schedule:
  TogoInuShitsukeHiroba::FriendDogGenerator:
    every: '20m'
    class: TogoInuShitsukeHiroba::FriendDogGeneratorJob
